CREATE TABLE profissionais (
    id                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                       TEXT NOT NULL,
    registro_conselho          TEXT NOT NULL UNIQUE,
    especialidade_principal_id INTEGER NOT NULL REFERENCES especialidades(id),
    criado_em                  TIMESTAMPTZ NOT NULL DEFAULT now()
);
