CREATE TABLE atendimentos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_ref      BIGINT NOT NULL UNIQUE,
    paciente_id      INTEGER NOT NULL REFERENCES pacientes(id),
    profissional_id  INTEGER NOT NULL REFERENCES profissionais(id),
    condicao_id      INTEGER NOT NULL REFERENCES condicoes(id),
    tipo_questao_id  INTEGER NOT NULL REFERENCES tipos_questao(id),
    data_atendimento TIMESTAMPTZ NOT NULL,
    queixa           TEXT NOT NULL,
    conduta          TEXT NOT NULL,
    busca            TSVECTOR GENERATED ALWAYS AS (
                         to_tsvector('portuguese', coalesce(queixa, '') || ' ' || coalesce(conduta, ''))
                     ) STORED
);

CREATE INDEX ix_atendimentos_paciente     ON atendimentos(paciente_id);
CREATE INDEX ix_atendimentos_condicao     ON atendimentos(condicao_id);
CREATE INDEX ix_atendimentos_profissional ON atendimentos(profissional_id);
CREATE INDEX ix_atendimentos_data         ON atendimentos(data_atendimento);
CREATE INDEX ix_atendimentos_busca        ON atendimentos USING GIN (busca);
