CREATE TABLE exames (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atendimento_id BIGINT NOT NULL REFERENCES atendimentos(id) ON DELETE CASCADE,
    nome_exame     TEXT NOT NULL,
    data_exame     DATE NOT NULL,
    resultado      TEXT NOT NULL
);

CREATE INDEX ix_exames_atendimento ON exames(atendimento_id);
