CREATE TABLE agendamentos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id         INTEGER NOT NULL REFERENCES pacientes(id),
    profissional_id     INTEGER NOT NULL REFERENCES profissionais(id),
    especialidade_id    INTEGER NOT NULL REFERENCES especialidades(id),
    data_hora_agendada  TIMESTAMPTZ NOT NULL,
    data_hora_realizada TIMESTAMPTZ,
    status              TEXT NOT NULL
        CONSTRAINT ck_agendamentos_status
        CHECK (status IN ('agendada', 'confirmada', 'realizada', 'cancelada', 'nao_compareceu')),
    motivo              TEXT,
    observacoes         TEXT,
    duracao_minutos     INTEGER NOT NULL DEFAULT 30,
    lembrete_enviado    BOOLEAN NOT NULL DEFAULT FALSE,
    recorrente          BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em           TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_agendamentos_paciente     ON agendamentos(paciente_id);
CREATE INDEX ix_agendamentos_profissional ON agendamentos(profissional_id);
CREATE INDEX ix_agendamentos_especialidade ON agendamentos(especialidade_id);
CREATE INDEX ix_agendamentos_data         ON agendamentos(data_hora_agendada);
CREATE INDEX ix_agendamentos_status       ON agendamentos(status);
