CREATE TABLE log_auditoria (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id TEXT NOT NULL,
    acao      TEXT NOT NULL,
    detalhe   JSONB NOT NULL DEFAULT '{}',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_log_auditoria_sessao ON log_auditoria(sessao_id);
