-- ============================================================================
-- Schema de prontuários médicos (PostgreSQL 17 + pgvector)
-- *** ARQUIVO AUTO-GERADO *** Execute: python database/rebuild_schema.py
--
-- O placeholder __DIM__ é substituído pelo migrador conforme o modelo de
-- embeddings usado (384 p/ e5-local, 1536 p/ text-embedding-3-small).
-- Executável também via psql:  sed 's/__DIM__/384/' schema_postgres.sql | psql ...
-- ============================================================================


CREATE EXTENSION IF NOT EXISTS vector;



CREATE TABLE especialidades (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE
);



CREATE TABLE condicoes (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE
);



CREATE TABLE tipos_questao (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE
);



CREATE TABLE profissionais (
    id                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                       TEXT NOT NULL,
    registro_conselho          TEXT NOT NULL UNIQUE,
    especialidade_principal_id INTEGER NOT NULL REFERENCES especialidades(id),
    criado_em                  TIMESTAMPTZ NOT NULL DEFAULT now()
);



CREATE TABLE profissional_especialidade (
    profissional_id  INTEGER NOT NULL REFERENCES profissionais(id) ON DELETE CASCADE,
    especialidade_id INTEGER NOT NULL REFERENCES especialidades(id),
    PRIMARY KEY (profissional_id, especialidade_id)
);



CREATE TABLE pacientes (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            TEXT NOT NULL,
    cpf_mascarado   TEXT NOT NULL UNIQUE,
    data_nascimento DATE NOT NULL,
    sexo            TEXT NOT NULL CONSTRAINT ck_pacientes_sexo CHECK (sexo IN ('M', 'F')),
    telefone_mock   TEXT NOT NULL,
    criado_em       TIMESTAMPTZ NOT NULL DEFAULT now()
);



CREATE TABLE paciente_condicao (
    paciente_id      INTEGER NOT NULL REFERENCES pacientes(id) ON DELETE CASCADE,
    condicao_id      INTEGER NOT NULL REFERENCES condicoes(id),
    data_diagnostico DATE NOT NULL,
    status           TEXT NOT NULL
        CONSTRAINT ck_paciente_condicao_status CHECK (status IN ('ativo', 'cronico', 'resolvido')),
    PRIMARY KEY (paciente_id, condicao_id)
);

CREATE INDEX ix_paciente_condicao_condicao ON paciente_condicao(condicao_id);



CREATE TABLE atendimentos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_ref      BIGINT NOT NULL UNIQUE,
    paciente_id      INTEGER NOT NULL REFERENCES pacientes(id),
    profissional_id  INTEGER NOT NULL REFERENCES profissionais(id),
    condicao_id      INTEGER NOT NULL REFERENCES condicoes(id),
    tipo_questao_id  INTEGER NOT NULL REFERENCES tipos_questao(id),
    data_atendimento TIMESTAMPTZ NOT NULL,
    queixa           TEXT NOT NULL,
    conduta          TEXT NOT NULL,
    busca            TSVECTOR GENERATED ALWAYS AS (
                         to_tsvector('portuguese', coalesce(queixa, '') || ' ' || coalesce(conduta, ''))
                     ) STORED
);

CREATE INDEX ix_atendimentos_paciente     ON atendimentos(paciente_id);
CREATE INDEX ix_atendimentos_condicao     ON atendimentos(condicao_id);
CREATE INDEX ix_atendimentos_profissional ON atendimentos(profissional_id);
CREATE INDEX ix_atendimentos_data         ON atendimentos(data_atendimento);
CREATE INDEX ix_atendimentos_busca        ON atendimentos USING GIN (busca);



CREATE TABLE exames (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atendimento_id BIGINT NOT NULL REFERENCES atendimentos(id) ON DELETE CASCADE,
    nome_exame     TEXT NOT NULL,
    data_exame     DATE NOT NULL,
    resultado      TEXT NOT NULL
);

CREATE INDEX ix_exames_atendimento ON exames(atendimento_id);



CREATE TABLE agendamentos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id         INTEGER NOT NULL REFERENCES pacientes(id),
    profissional_id     INTEGER NOT NULL REFERENCES profissionais(id),
    especialidade_id    INTEGER NOT NULL REFERENCES especialidades(id),
    data_hora_agendada  TIMESTAMPTZ NOT NULL,
    data_hora_realizada TIMESTAMPTZ,
    status              TEXT NOT NULL
        CONSTRAINT ck_agendamentos_status
        CHECK (status IN ('agendada', 'confirmada', 'realizada', 'cancelada', 'nao_compareceu')),
    motivo              TEXT,
    observacoes         TEXT,
    duracao_minutos     INTEGER NOT NULL DEFAULT 30,
    lembrete_enviado    BOOLEAN NOT NULL DEFAULT FALSE,
    recorrente          BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em           TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_agendamentos_paciente     ON agendamentos(paciente_id);
CREATE INDEX ix_agendamentos_profissional ON agendamentos(profissional_id);
CREATE INDEX ix_agendamentos_especialidade ON agendamentos(especialidade_id);
CREATE INDEX ix_agendamentos_data         ON agendamentos(data_hora_agendada);
CREATE INDEX ix_agendamentos_status       ON agendamentos(status);



CREATE TABLE prontuario_chunks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atendimento_id   BIGINT NOT NULL REFERENCES atendimentos(id) ON DELETE CASCADE,
    ordem_chunk      INTEGER NOT NULL,
    conteudo         TEXT NOT NULL,
    embedding        VECTOR(__DIM__),
    modelo_embedding TEXT,
    dimensoes        INTEGER,
    UNIQUE (atendimento_id, ordem_chunk),
    CONSTRAINT ck_prontuario_chunks_embedding
        CHECK (embedding IS NULL OR (modelo_embedding IS NOT NULL AND dimensoes IS NOT NULL))
);

CREATE INDEX ix_prontuario_chunks_atendimento ON prontuario_chunks(atendimento_id);
CREATE INDEX ix_prontuario_chunks_embedding
    ON prontuario_chunks USING hnsw (embedding vector_cosine_ops);



CREATE TABLE log_auditoria (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id TEXT NOT NULL,
    acao      TEXT NOT NULL,
    detalhe   JSONB NOT NULL DEFAULT '{}',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_log_auditoria_sessao ON log_auditoria(sessao_id);



CREATE VIEW vw_historico_paciente AS
SELECT
    a.id               AS atendimento_id,
    a.paciente_id,
    pa.nome            AS paciente,
    c.nome             AS condicao,
    tq.nome            AS tipo_questao,
    pr.nome            AS profissional,
    e.nome             AS especialidade_principal,
    a.data_atendimento,
    a.queixa,
    a.conduta
FROM atendimentos a
JOIN pacientes      pa ON pa.id = a.paciente_id
JOIN condicoes      c  ON c.id  = a.condicao_id
JOIN tipos_questao  tq ON tq.id = a.tipo_questao_id
JOIN profissionais  pr ON pr.id = a.profissional_id
JOIN especialidades e  ON e.id = pr.especialidade_principal_id;



CREATE VIEW vw_exames_paciente AS
SELECT
    e.id             AS exame_id,
    e.atendimento_id,
    a.paciente_id,
    e.nome_exame,
    e.data_exame,
    e.resultado
FROM exames e
JOIN atendimentos a ON a.id = e.atendimento_id;



CREATE VIEW vw_estatisticas_base AS
SELECT
    (SELECT COUNT(*) FROM pacientes)      AS pacientes,
    (SELECT COUNT(*) FROM profissionais)  AS profissionais,
    (SELECT COUNT(*) FROM atendimentos)   AS atendimentos,
    (SELECT COUNT(*) FROM condicoes)      AS condicoes,
    (SELECT COUNT(*) FROM especialidades) AS especialidades,
    (SELECT COUNT(*) FROM exames)         AS exames,
    (SELECT COUNT(*) FROM log_auditoria)  AS logs_auditoria,
    (SELECT COUNT(*) FROM agendamentos)   AS agendamentos;


